import * as inspirationsService from '../../../inspirations/inspirations-service';

export const seed = async (): Promise<void> => {
  const inspirations = [
    'Organize your dresser',
    'Take your cat on a walk',
    'Paint the first thing you see',
    'Meditate for five minutes',
    'Organize your dresser',
    'Organize a bookshelf',
    'Learn how to make a website',
    'Make a scrapbook with pictures of your favorite memories',
    "Clean out your closet and donate the clothes you've outgrown",
    'Pull a harmless prank on one of your friends',
    'Organize a bookshelf',
    'Look at your finances and find one way to save money',
    'Take a nap',
    'Sit in the dark and listen to your favorite music with no distractions',
    'Teach your dog a new trick',
    'Go to a concert with some friends',
    'Catch up on world news',
    'Bake pastries for you and your neighbor',
    'Volunteer and help out at a senior center',
    'Learn how to write in shorthand',
    'Watch the sunset or the sunrise',
    'Watch a classic movie',
    'Learn to sew on a button',
    'Go see a movie in theaters with a few friends',
    'Learn and play a new card game',
    'Do something you used to do as a kid',
    'Go to a nail salon',
    'Organize a bookshelf',
    'Bake a pie with some friends',
    'Meditate for five minutes',
    'Write a note of appreciation to someone',
    'Go see a movie in theaters with a few friends',
    'Create and follow a savings plan',
    'Start a collection',
    'Practice coding in your favorite lanaguage',
    'Memorize the fifty states and their capitals',
    'Learn GraphQL',
    'Pick up litter around your favorite park',
    'Draw and color a Mandala',
    "Plan a vacation you've always wanted to take",
    'Go to a concert with some friends',
    "Try a food you don't like",
    'Have a paper airplane contest with some friends',
    'Invite some friends over for a game night',
    'Play basketball with a group of friends',
    'Meditate for five minutes',
    'Learn about the Golden Ratio',
    "Shred old documents you don't need anymore",
    'Learn to write with your nondominant hand',
    'Memorize the fifty states and their capitals',
    "Solve a Rubik's cube",
    'Mow your lawn',
    'Watch a classic movie',
    'Draw something interesting',
    'Make a simple musical instrument',
    'Learn how to use an Arduino',
    'Play a video game',
    'Visit your past teachers',
    'Organize a cluttered drawer',
    'Make a bucket list',
    'Clean out your car',
    "Research a topic you're interested in",
    'Explore a park you have never been to before',
    'Surprise your significant other with something considerate',
    'Draft your living will',
    'Learn GraphQL',
    'Start a daily journal',
    "Mow your neighbor's lawn",
    'Have a bonfire with your close friends',
    'Teach your dog a new trick',
    'Listen to a new music genre',
    'Bake pastries for you and your neighbor',
    'Organize a bookshelf',
    'Go to a karaoke bar with some friends',
    'Prepare a 72-hour kit',
    'Write a song',
    "Listen to music you haven't heard in a while",
    'Shop at support your local farmers market',
    'Make a to-do list for your week',
    'Have a bonfire with your close friends',
    'Organize your music collection',
    'Go to an escape room',
    'Go to a nail salon',
    'Explore the nightlife of your city',
    'Compliment someone',
    'Make a budget',
    'Go for a run',
    'Watch a classic movie',
    'Learn origami',
    'Learn about the Golden Ratio',
    "Research a topic you're interested in",
    'Hold a video game tournament with some friends',
    'Learn the Chinese erhu',
    'Learn to sew on a button',
    'Learn how to french braid hair',
    'Learn a new recipe',
    'Memorize the fifty states and their capitals',
    'Wash your car',
    'Learn how to write in shorthand',
    'Hold a yard sale',
    'Prepare a dish from a foreign culture',
    'Go to a karaoke bar with some friends',
    'Organize your music collection',
    'Go on a fishing trip with some friends',
    'Clean out your car',
    'Improve your touch typing',
    'Learn how to play a new sport',
    'Watch a classic movie',
    'Take a class at your local community center that interests you',
    "Bake something you've never tried before",
    'Make a to-do list for your week',
    'Create a personal website',
    'Surprise your significant other with something considerate',
    'Take a spontaneous road trip with some friends',
    'Sit in the dark and listen to your favorite music with no distractions',
    'Organize your dresser',
    'Write a thank you letter to an influential person in your life',
    'Study a foreign language',
    'Make a to-do list for your week',
    'Learn to sew on a button',
    'Learn to sew on a button',
    'Donate blood at a local blood center',
    'Have a picnic with some friends',
    'Learn about a distributed version control system such as Git',
    "Listen to music you haven't heard in a while",
    'Learn calligraphy',
    'Donate blood at a local blood center',
    'Organize your music collection',
    'Rearrange and organize your room',
    'Practice coding in your favorite lanaguage',
    'Catch up with a friend over a lunch date',
    'Uninstall unused apps from your devices',
    'Study a foreign language',
    'Go to a music festival with some friends',
    'Volunteer at your local food bank',
    'Learn to play a new instrument',
    'Organize your dresser',
    'Do something nice for someone you care about',
    'Go to the library and find an interesting book',
    "Start a blog for something you're passionate about",
    'Organize your movie collection',
    'Clean out your garage',
    'Listen to your favorite album',
    'Have a picnic with some friends',
    'Sit in the dark and listen to your favorite music with no distractions',
    'Write a poem',
    'Go to a music festival with some friends',
    'Make bread from scratch',
    'Catch up with a friend over a lunch date',
    'Take a bubble bath',
    'Go to a concert with some friends',
    'Make a bucket list',
    'Volunteer at your local food bank',
    'Clean out your refrigerator',
    'Write a song',
    'Play basketball with a group of friends',
    'Create and follow a savings plan',
    'Go to a local thrift shop',
    'Do a jigsaw puzzle',
    'Donate blood at a local blood center',
    'Read a formal research paper on an interesting subject',
    "Bake something you've never tried before",
    'Learn a new recipe',
    'Look at pictures and videos of cute animals',
    'Volunteer and help out at a senior center',
    'Take a caffeine nap',
    'Have a jam session with your friends',
    'Take a bubble bath',
    'Organize your music collection',
    'Play a game of tennis with a friend',
    'Sit in the dark and listen to your favorite music with no distractions',
    'Go swimming with a friend',
    'Prepare a dish from a foreign culture',
    "Start a blog for something you're passionate about",
    'Binge watch a trending series',
    'Look at your finances and find one way to save money',
    'Look at your finances and find one way to save money',
    'Go see a Broadway production',
    'Hold a yard sale',
    'Watch a classic movie',
    'Teach your dog a new trick',
    'Learn and play a new card game',
    'Pull a harmless prank on one of your friends',
    'Visit your past teachers',
    'Create a compost pile',
    'Write a list of things you are grateful for',
    'Go to a nail salon',
    'Listen to a new podcast',
    'Create a cookbook with your favorite recipes',
    'Explore a park you have never been to before',
    'Conquer one of your fears',
    "Start a book you've never gotten around to reading",
    'Make a new friend',
    'Go swimming with a friend',
    "Start a blog for something you're passionate about",
    "Clean out your closet and donate the clothes you've outgrown",
    'Create a personal website',
    'Plan a trip to another country',
    'Surprise your significant other with something considerate',
    'Repaint a room in your house',
    'Color',
    'Hold a yard sale',
    'Watch a Khan Academy lecture on a subject of your choosing',
    'Start a garden',
    'Learn Kotlin',
    'Organize your movie collection',
    'Invite some friends over for a game night',
    'Learn how to use a french press',
    'Learn how to make a website',
    'Have a football scrimmage with some friends',
    'Meditate for five minutes',
    'Make a budget',
    'Organize your dresser',
    'Watch the sunset or the sunrise',
    'Learn a new programming language',
    'Create a cookbook with your favorite recipes',
    'Go to a concert with some friends',
    'Sit in the dark and listen to your favorite music with no distractions',
    'Make a simple musical instrument',
    'Pot some plants and put them around your house',
    'Study a foreign language',
    'Surprise your significant other with something considerate',
    'Start a band',
    'Make homemade ice cream',
    'Paint the first thing you see',
    'Read a formal research paper on an interesting subject',
    'Write a thank you letter to an influential person in your life',
    'Look at your finances and find one way to save money',
    'Create a personal website',
    'Go stargazing',
    'Learn to sew on a button',
    'Learn how to whistle with your fingers',
    'Take a caffeine nap',
    'Prepare a 72-hour kit',
    'Start a band',
    'Visit a nearby museum',
    'Donate blood at a local blood center',
    'Go to an escape room',
    'Pot some plants and put them around your house',
    'Go on a fishing trip with some friends',
    'Mow your lawn',
    'Learn a new programming language',
    'Learn to greet someone in a new language',
    'Go for a walk',
    'Do yoga',
    'Paint the first thing you see',
    'Start a collection',
    'Listen to a new music genre',
    'Pick up litter around your favorite park',
    'Write a short story',
    'Learn to greet someone in a new language',
    'Take a bubble bath',
    'Create a personal website',
    'Pull a harmless prank on one of your friends',
    'Create a cookbook with your favorite recipes',
    'Go for a run',
    'Learn and play a new card game',
    'Pot some plants and put them around your house',
    'Create a compost pile',
    'Play a video game',
    'Take your cat on a walk',
    "Plan a vacation you've always wanted to take",
    "Text a friend you haven't talked to in a long time",
    'Look at your finances and find one way to save money',
    'Wash your car',
    'Volunteer at a local animal shelter',
    'Repaint a room in your house',
    'Make a scrapbook with pictures of your favorite memories',
    'Volunteer at your local food bank',
    'Play a video game',
    'Play a volleyball match with some friends',
    "Mow your neighbor's lawn",
    'Invite some friends over for a game night',
    'Buy a new house decoration',
    'Take a class at your local community center that interests you',
    'Teach your dog a new trick',
    'Take a hike at a local park',
    'Volunteer at your local food pantry',
    'Back up important computer files',
    'Make a bucket list',
    'Uninstall unused apps from your devices',
    'Learn Morse code',
    'Learn to play a new instrument',
    "Try a food you don't like",
    'Learn about the Golden Ratio',
    'Learn how the internet works',
    'Make homemade ice cream',
    "Resolve a problem you've been putting off",
    'Learn about the Golden Ratio',
    'Learn the periodic table',
    'Binge watch a trending series',
    'Have a football scrimmage with some friends',
    'Learn about a distributed version control system such as Git',
    "Solve a Rubik's cube",
    'Do a jigsaw puzzle',
    'Learn and play a new card game',
    'Create a cookbook with your favorite recipes',
    'Back up important computer files',
    'Buy a new house decoration',
    'Surprise your significant other with something considerate',
    'Bake pastries for you and your neighbor',
    'Hold a yard sale',
    'Learn to write with your nondominant hand',
    'Make a simple musical instrument',
    'Paint the first thing you see',
    'Invite some friends over for a game night',
    'Pot some plants and put them around your house',
    "Mow your neighbor's lawn",
    'Create a compost pile',
    'Start a webinar on a topic of your choice',
    'Learn about a distributed version control system such as Git',
    'Catch up on world news',
    'Go to an escape room',
    'Bake pastries for you and your neighbor',
    'Study a foreign language',
    'Take a class at your local community center that interests you',
    'Start a family tree',
    'Bake a pie with some friends',
    'Give your pet ten minutes of focused attention',
    'Make a scrapbook with pictures of your favorite memories',
    'Wash your car',
    'Write a short story',
    'Organize your music collection',
    'Go to the gym',
    "Try a food you don't like",
    'Play a game of Monopoly',
    'Start a webinar on a topic of your choice',
    "Fix something that's broken in your house",
    'Make a bucket list',
    'Learn how to use a french press',
    'Organize your movie collection',
    'Go to the gym',
    'Learn the NATO phonetic alphabet',
    'Go to a concert with some friends',
    'Write a short story',
    'Have a photo session with some friends',
    'Learn calligraphy',
    'Learn origami',
    'Learn how to play a new sport',
    'Learn how to use an Arduino',
    'Write a thank you letter to an influential person in your life',
    "Solve a Rubik's cube",
    'Make a bucket list',
    'Listen to your favorite album',
    'Host a movie marathon with some friends',
    'Create or update your resume',
    'Start a webinar on a topic of your choice',
    'Organize your pantry',
    'Play a game of tennis with a friend',
    'Start a band',
    'Mow your lawn',
    "Try a food you don't like",
    'Donate to your local food bank',
    'Go on a long drive with no music',
    'Make a simple musical instrument',
    'Play a game of tennis with a friend',
    'Write a thank you letter to an influential person in your life',
    'Take a bubble bath',
    'Organize your basement',
    'Look at your finances and find one way to save money',
    "Text a friend you haven't talked to in a long time",
    'Learn how to fold a paper crane',
    'Organize a cluttered drawer',
    'Volunteer at your local food pantry',
    'Look at pictures and videos of cute animals',
    "Watch a movie you'd never usually watch",
  ];

  await Promise.all(
    inspirations.map(
      async (activity) => await inspirationsService.createInspiration(activity)
    )
  );
};
